version: 2.1

commands:
  runtests:
    description: Run tests using npm
    steps:
      - run:
          name: NodeJS version
          command: node -v

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package.json" }}

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

jobs:
  node-current: 
    docker:
      - image: circleci/node:current

    working_directory: ~/customerio-node

    steps:
      - checkout
      - runtests

  node-10:
    docker:
      - image: circleci/node:10

    working_directory: ~/customerio-node

    steps:
      - checkout
      - runtests
  
  node-12:
    docker:
      - image: circleci/node:12

    working_directory: ~/customerio-node

    steps:
      - checkout
      - runtests

  node-14:
    docker:
      - image: circleci/node:14

    working_directory: ~/customerio-node

    steps:
      - checkout
      - runtests

workflows:
  version: 2
  test:
    jobs:
      - node-current
      - node-10
      - node-12
      - node-14
